# .streamlit/secrets.toml
SECRET_KEY = "kL9s8D3f7G2a1J0pQ4rM6xZ5nB8tV1wU"
MONGO_URI = "mongodb+srv://shapuramvedanthreddy_db_user:kyNIkrEaOzK5Ovuc@cluster0.7e1g9hm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
SMTP_USER = "vedhu2586reddy@gmail.com"
SMTP_PASS = "himx tmnc ittl xlct"
CURRENCY_BASE = "USD"
